name: "Clang Static Analyzer"

on:
  push:
    branches:
      - 'master'
      - '202[0-9][0-9][0-9]'
  pull_request:
    branches:
      - 'master'
      - '202[0-9][0-9][0-9]'
  workflow_dispatch:

jobs:
  analyze:
    name: ClangSA Analysis
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tools-14 \
            libxml-simple-perl \
            aspell \
            aspell-en \
            libhiredis-dev \
            libnl-3-dev \
            libnl-genl-3-dev \
            libnl-route-3-dev \
            libnl-nf-3-dev \
            libyang-dev \
            libzmq3-dev \
            libzmq5 \
            swig4.0 \
            libpython3-dev \
            libgtest-dev \
            libgmock-dev \
            libboost-dev \
            libboost-serialization-dev \
            dh-exec \
            doxygen \
            cdbs \
            bison \
            flex \
            graphviz \
            autoconf-archive \
            uuid-dev \
            libjansson-dev \
            nlohmann-json3-dev

    - name: Build sonic-swss-common
      run: |
        cd ..
        git clone https://github.com/sonic-net/sonic-swss-common
        pushd sonic-swss-common
        ./autogen.sh
        dpkg-buildpackage -rfakeroot -us -uc -b -Pnoyangmod,nopython2 -j$(nproc)
        popd
        dpkg-deb -x libswsscommon_${SWSSCOMMON_VER}_amd64.deb $(dirname $GITHUB_WORKSPACE)
        dpkg-deb -x libswsscommon-dev_${SWSSCOMMON_VER}_amd64.deb $(dirname $GITHUB_WORKSPACE)
      env:
        SWSSCOMMON_VER: "1.0.0"

    - name: Run Clang Static Analyzer
      run: |
        ./autogen.sh
        SWSS_COMMON_INC="$(dirname $GITHUB_WORKSPACE)/usr/include" \
        SWSS_COMMON_LIB="$(dirname $GITHUB_WORKSPACE)/usr/lib/x86_64-linux-gnu" \
        scan-build-14 -o /tmp/scan-build-reports \
          ./configure --with-sai=vs --disable-python2 \
            --with-swss-common-inc="$(dirname $GITHUB_WORKSPACE)/usr/include" \
            --with-swss-common-lib="$(dirname $GITHUB_WORKSPACE)/usr/lib/x86_64-linux-gnu" \
            CXXFLAGS="-std=c++14 -Wno-error" CFLAGS="-Wno-error"
        scan-build-14 -o /tmp/scan-build-reports make -j$(nproc)

    - name: Upload scan-build reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: clangsa-reports
        path: /tmp/scan-build-reports/
        retention-days: 14
